version: "3"

services:
  node:
    tty: true
    build: .
    volumes:
      - ./app:/app
    ports:
      - "3000"
    depends_on:
      - "mysql"
      - "redis"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - "node"
  mysql:
    build: ./mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/sqls:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    command: --innodb-use-native-aio=0
  redis:
    image: redis:5.0.5
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: redis-server --appendonly yes
  gulp:
    build: ./gulp
    tty: true
    volumes:
      - ./app/css:/home/node/dist/css:z
      - ./gulp:/home/node